apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: davmaio-jupyter38
  annotations:
    version: 0.0.1
    description: "Jupyter Notebook is a web-based interactive computing platform."
spec:
  components:
    - componentName: davmaio-jupyter38
      traits:
        - trait:
            apiVersion: core.napptive.com/v1alpha1
            kind: Ingress
            metadata:
              name: davmaio-jupyter38-ingress
            spec:
              name: davmaio-jupyter38
              protocol: HTTP
              port: 8888
              path: /
              rewritePath: /
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: davmaio-jupyter38-trait
            spec:
              replicaCount: 1
      scopes:
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: HealthScope
            name: davmaio-jupyter38-health