apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: davmaio-jupyterult38
  annotations:
    version: 1.1.0
    description: "Jupyter Notebook is a web-based interactive computing platform."
spec:
  components:
    - name: davmaio-jupyterult38
      type: webservice
      properties:
        image: davma/jupyter-ultimate:3.8
        ports:
          - port: 8888
            expose: true
        cpu: "1000m"
        memory: "1000Mi"
      traits:
        - type: napptive-ingress         
          properties:
            name: davmaio-jupyterult
            port: 8888
            path: /
            rewritePath: /
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: davmaio-jupyterult38-health
      type: health
      properties:
        probeInterval: 5