apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: davmaio-jupyter310
  annotations:
    version: 0.0.1
    description: "Jupyter Notebook is a web-based interactive computing platform."
spec:
  components:
    - name: davmaio-jupyter310
      type: webservice
      properties:
        image: davma/jupyter-tensorflow-pyodbc:3.10
        ports:
          - port: 8888
            expose: true
        cpu: "500m"
        memory: "500Mi"
      traits:
        - type: napptive-ingress         
          properties:
            name: davmaio-grafana
            port: 8888
            path: /
            rewritePath: /
        - type: scaler
          properties:
            replicas: 1
  policies:
    - name: davmaio-jupyter39-health
      type: health
      properties:
        probeInterval: 5